### PR TITLE
Removing internal IP addresses from initial dataset

### PR DESCRIPTION
**Pull request by nstarke**
There are internal IP addresses sprinkled throughout the source - I have removed them and replaced the address with a hostname of 'geoserver'. This might break someone's development environment, but its generally bad practice to hardcode internal network information within a git repository.  While not exactly sensitive, such information can be used in malicious ways.

Please let me know if I can be of further service or clarify / modify my changes.

### CODE REVIEW

**Comment by stephenrjones** [comment]
Thanks Nicholas -- we received your change and have put it on our list. We have a monthly get-together to review pull requests and approve them -- once we've gone through that, you'll most likely see your changes pushed up to the server.

**Comment by nstarke** [comment]
Hi Stephen, thanks for the clarification.  Please let me know if there is anything you need from me to land this commit.

**Comment by nstarke** [comment]
This PR has been open for over a year - as such I want to start a conversation on whether there is any value in this commit.  I completely understand if this needs to be rejected, and would be happy to close this pull request if that is the case.

**Comment by stephenrjones** [comment]
We've gone through and checked that the internal ip's listed are no longer valid. Thanks for the input.

**Pull request closed without merging**
